name: Markdown

on:
  pull_request:
    branches: [main]

jobs:
  prettier:
    name: Verify formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install
        run: |
          yarn install
      - name: Run check
        run: |
          yarn prettier --check docs/*.md* docs/**/*.md* docs/**/**/*.md*
